- src_path: .
  dest_path: /tmp/aaa
  # Only a subset of rsync filter rules is supported
  ignores:
    - dist-newstyle
    - stack.yaml.lock
    - "*.hp"
  rsync_opts:
    - --exclude local-data
    - --exclude .stack-work
